[book]
authors = ["Jean-Louis Fuchs"]
language = "en"
multilingual = false
src = "src"
title = "BitBook"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
additional-css = ["theme/css/user.css"]
